In [16]:
import pandas as pd   #importing the file


df = pd.read_excel(r"C:\Users\beles\OneDrive\Desktop\cv portfolio\SQL - Retail Sales Analysis_utf .xlsb", engine='pyxlsb')

data_array = df.to_numpy(dtype=str)

In [5]:
print(df.columns)       # Show all column names
print(df.head())        # Show first 5 rows



Index(['transactions_id', 'sale_date', 'sale_time', 'customer_id', 'gender',
       'age', 'category', 'quantiy', 'price_per_unit', 'cogs', 'total_sale'],
      dtype='object')
   transactions_id  sale_date  sale_time  customer_id  gender   age  category  \
0              180      44870   0.449306          117    Male  41.0  Clothing   
1              522      44751   0.458333           52    Male  46.0    Beauty   
2              559      44907   0.450000            5  Female  40.0  Clothing   
3             1180      44567   0.370139           85    Male  41.0  Clothing   
4             1522      44879   0.357639           48    Male  46.0    Beauty   

   quantiy  price_per_unit   cogs  total_sale  
0      3.0           300.0  129.0       900.0  
1      3.0           500.0  145.0      1500.0  
2      4.0           300.0   84.0      1200.0  
3      3.0           300.0  129.0       900.0  
4      3.0           500.0  235.0      1500.0  


In [6]:
import numpy as np

df_clean = df.dropna() # droping missing rows

data_array = df_clean.to_numpy() # convert to numpy array

print("Shape:", data_array.shape)
print(data_array[:5])   # cheking the shape and previewing the first 5 rows

Shape: (1987, 11)
[[180 44870 0.44930555555555557 117 'Male' 41.0 'Clothing' 3.0 300.0
  129.0 900.0]
 [522 44751 0.4583333333333333 52 'Male' 46.0 'Beauty' 3.0 500.0 145.0
  1500.0]
 [559 44907 0.45 5 'Female' 40.0 'Clothing' 4.0 300.0 84.0 1200.0]
 [1180 44567 0.3701388888888889 85 'Male' 41.0 'Clothing' 3.0 300.0 129.0
  900.0]
 [1522 44879 0.3576388888888889 48 'Male' 46.0 'Beauty' 3.0 500.0 235.0
  1500.0]]


In [7]:
total_sales = data_array[:, -1].astype(float) #selecting all the rows and converting them in to floating point numbers#

print("Total Sales:", np.sum(total_sales)) # the sum off the total sales

print("Avarage sales:", np.mean(total_sales)) # the avatage off the total sales 

print("Max sales:", np.max(total_sales)) # the maximum value off the total sales


Total Sales: 908230.0
Avarage sales: 457.0860593860091
Max sales: 2000.0


In [ ]:
categories = data_array[:, 6] # extracting the 7th column from the data base

unique, counts = np.unique(categories, return_counts=True) # identifying the unique categories and counting them

category_summary = sorted(zip(unique, counts), key=lambda x: x[1], reverse=True) # combinating and sorting


print("Most common product categories:")
for cat, count in category_summary:
    print(f"{cat}: {count}")

Most common product categories:
Clothing: 698
Electronics: 678
Beauty: 611


In [ ]:
prices = data_array[:, 8].astype(float)  # 9th column is price

print("Price statistics:")
print("Min:", np.min(prices))
print("Max:", np.max(prices))
print("Average:", np.mean(prices))
print("Median:", np.median(prices))



Price statistics:
Min: 25.0
Max: 500.0
Average: 179.92450931051837
Median: 50.0


In [10]:
expensive = data_array[prices > 100] # outputing the prices that are more than 100 euro

print("products over 100 euro:")
print(expensive)

products over 100 euro:
[[180 44870 0.44930555555555557 ... 300.0 129.0 900.0]
 [163 44865 0.4013888888888889 ... 50.0 23.0 150.0]
 [1163 44685 0.4527777777777778 ... 50.0 27.0 150.0]
 ...
 [1429 45252 0.5513888888888889 ... 25.0 12.0 50.0]
 [1989 44810 0.68125 ... 25.0 13.25 25.0]
 [1857 44874 0.5104166666666666 ... 25.0 7.5 50.0]]


In [19]:
dates = data_array[:, 0]  # Assuming first column is dates in 'YYYY-MM-DD' format

months = [date[:7] for date in dates]  # Extract 'YYYY-MM'

unique_months, month_counts = np.unique(months, return_counts=True)

print("Sales per month:")
for m, count in zip(unique_months, month_counts):
    print(f"{m}: {count}")

    
    

Sales per month:
1: 1
10: 1
100: 1
1000: 1
1001: 1
1002: 1
1003: 1
1004: 1
1005: 1
1006: 1
1007: 1
1008: 1
1009: 1
101: 1
1010: 1
1011: 1
1012: 1
1013: 1
1014: 1
1015: 1
1016: 1
1017: 1
1018: 1
1019: 1
102: 1
1020: 1
1021: 1
1022: 1
1023: 1
1024: 1
1025: 1
1026: 1
1027: 1
1028: 1
1029: 1
103: 1
1030: 1
1031: 1
1032: 1
1033: 1
1034: 1
1035: 1
1036: 1
1037: 1
1038: 1
1039: 1
104: 1
1040: 1
1041: 1
1042: 1
1043: 1
1044: 1
1045: 1
1046: 1
1047: 1
1048: 1
1049: 1
105: 1
1050: 1
1051: 1
1052: 1
1053: 1
1054: 1
1055: 1
1056: 1
1057: 1
1058: 1
1059: 1
106: 1
1060: 1
1061: 1
1062: 1
1063: 1
1064: 1
1065: 1
1066: 1
1067: 1
1068: 1
1069: 1
107: 1
1070: 1
1071: 1
1072: 1
1073: 1
1074: 1
1075: 1
1076: 1
1077: 1
1078: 1
1079: 1
108: 1
1080: 1
1081: 1
1082: 1
1083: 1
1084: 1
1085: 1
1086: 1
1087: 1
1088: 1
1089: 1
109: 1
1090: 1
1091: 1
1092: 1
1093: 1
1094: 1
1095: 1
1096: 1
1097: 1
1098: 1
1099: 1
11: 1
110: 1
1100: 1
1101: 1
1102: 1
1103: 1
1104: 1
1105: 1
1106: 1
1107: 1
1108: 1
1109: 1
111: 1
11